version: '3.9'
services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api/data:/app/data
    restart: always

  agent:
    build:
      context: ./agent
    environment:
      - API_URL=http://api:5000/collect
    depends_on:
      - api
    restart: on-failure
